# Generated by Django 4.2.20 on 2025-06-10 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10)),
                ('nacionalidad', models.CharField(default='Dominicana', max_length=50)),
                ('telefono_principal', models.CharField(max_length=15)),
                ('telefono_secundario', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('DN', 'Distrito Nacional'), ('SD', 'Santo Domingo'), ('SDE', 'Santo Domingo Este'), ('SA', 'Santiago'), ('PU', 'Puerto Plata'), ('LA', 'La Altagracia'), ('VE', 'La Vega'), ('SP', 'San Pedro de Macorís'), ('SC', 'San Cristóbal'), ('HR', 'Hermanas Mirabal')], max_length=3)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=10)),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleador', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_laboral', models.CharField(blank=True, max_length=15, null=True)),
                ('banco_principal', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_despacho', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque')], max_length=20)),
                ('departamento', models.CharField(choices=[('ayuntamiento', 'Ayuntamiento'), ('ferquido', 'Ferquido')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestamos.cliente')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_recibo', models.CharField(help_text='Número único que identifica el recibo', max_length=50, unique=True, verbose_name='Número de Recibo')),
                ('monto_pago', models.DecimalField(decimal_places=2, help_text='Monto del pago recibido', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó el pago', verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro método')], default='EFECTIVO', help_text='Método utilizado para el pago', max_length=20, verbose_name='Método de Pago')),
                ('tipo_pago', models.CharField(choices=[('COMPLETO', 'Pago Completo'), ('ABONO', 'Abono')], default='COMPLETO', help_text='Tipo de pago: Pago Completo o Abono', max_length=20, verbose_name='Tipo de Pago')),
                ('notas', models.TextField(blank=True, help_text='Observaciones o detalles adicionales sobre el pago', null=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el ingreso en el sistema', verbose_name='Fecha de Registro')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingreso',
                'ordering': ['-fecha_pago', '-no_recibo'],
            },
        ),
    ]
