# Generated by Django 4.2.20 on 2025-06-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10)),
                ('nacionalidad', models.CharField(default='Dominicana', max_length=50)),
                ('telefono_principal', models.CharField(max_length=15)),
                ('telefono_secundario', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('DN', 'Distrito Nacional'), ('SD', 'Santo Domingo'), ('SDE', 'Santo Domingo Este'), ('SA', 'Santiago'), ('PU', 'Puerto Plata'), ('LA', 'La Altagracia'), ('VE', 'La Vega'), ('SP', 'San Pedro de Macorís'), ('SC', 'San Cristóbal'), ('HR', 'Hermanas Mirabal')], max_length=3)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=10)),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleador', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_laboral', models.CharField(blank=True, max_length=15, null=True)),
                ('banco_principal', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
