# Generated by Django 4.2.20 on 2025-06-10 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 5, 56, 40, 99811, tzinfo=datetime.timezone.utc)),
        ),
    ]
