# Generated by Django 4.2.20 on 2025-06-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='numero_factura',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
