# Generated by Django 4.2.20 on 2025-06-10 13:26

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, help_text='Monto del pago recibido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Pago'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 13, 26, 46, 953096, tzinfo=datetime.timezone.utc)),
        ),
    ]
