# Generated by Django 4.2.20 on 2025-06-18 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_ingreso_monto_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 2, 21, 16, 294811, tzinfo=datetime.timezone.utc)),
        ),
    ]
