# Generated by Django 4.2.20 on 2025-06-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_prestamo_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
    ]
