# Generated by Django 4.2.20 on 2025-06-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='numero_factura',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Factura'),
        ),
    ]
