# Generated by Django 4.2.20 on 2025-06-23 02:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0004_alter_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='anulado',
            field=models.BooleanField(default=False, help_text='Indica si el recibo ha sido anulado', verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='anulado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la anulación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anulaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_anulacion',
            field=models.DateField(blank=True, help_text='Fecha en que se anuló el recibo', null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='motivo_anulacion',
            field=models.CharField(blank=True, choices=[('ERROR_MONTO', 'Error en el monto'), ('RECIBO_DUPLICADO', 'Recibo duplicado'), ('SOLICITUD_CLIENTE', 'Solicitud del cliente'), ('ERROR_SISTEMA', 'Error del sistema'), ('OTRO', 'Otro')], help_text='Motivo por el cual se anuló el recibo', max_length=20, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='notas_anulacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la anulación', null=True, verbose_name='Notas de Anulación'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 2, 31, 10, 927302, tzinfo=datetime.timezone.utc)),
        ),
    ]
