# Generated by Django 4.2.20 on 2025-06-23 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_ingreso_anulado_ingreso_anulado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 2, 50, 50, 258294, tzinfo=datetime.timezone.utc)),
        ),
    ]
