# Generated by Django 4.2.20 on 2025-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo_telefono_alter_prestamo_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
