# Generated by Django 4.2.20 on 2025-06-23 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0006_alter_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 23, 17, 57, 59, 976403, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='RecibosAnulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_recibo', models.CharField(max_length=50, verbose_name='Número de Recibo')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(max_length=20, verbose_name='Método de Pago')),
                ('tipo_pago', models.CharField(max_length=20, verbose_name='Tipo de Pago')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('motivo_anulacion', models.CharField(max_length=20, verbose_name='Motivo de Anulación')),
                ('notas_anulacion', models.TextField(verbose_name='Notas de Anulación')),
                ('fecha_anulacion', models.DateField(verbose_name='Fecha de Anulación')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_anulados', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Recibo Anulado',
                'verbose_name_plural': 'Recibos Anulados',
                'ordering': ['-fecha_anulacion'],
            },
        ),
    ]
