# Generated by Django 4.2.20 on 2025-06-26 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_alter_prestamo_fecha_vencimiento_recibosanulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('DN', 'Distrito Nacional'), ('SD', 'Santo Domingo'), ('SDE', 'Santo Domingo Este'), ('SA', 'Santiago'), ('PU', 'Puerto Plata'), ('LA', 'La Altagracia'), ('VE', 'La Vega'), ('SP', 'San Pedro de Macorís'), ('SC', 'San Cristóbal'), ('HR', 'Hermanas Mirabal'), ('MC', 'Montecristi')], max_length=3),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 26, 17, 6, 28, 286392, tzinfo=datetime.timezone.utc)),
        ),
    ]
