# Generated by Django 4.2.20 on 2025-06-24 21:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_alter_prestamo_fecha_vencimiento_recibosanulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 24, 21, 37, 10, 302589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='OtroPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.CharField(choices=[('personal', 'Préstamo Personal'), ('vehiculo', 'Préstamo para Vehículo'), ('vivienda', 'Préstamo para Vivienda'), ('negocio', 'Préstamo para Negocio'), ('emergencia', 'Préstamo de Emergencia'), ('educacion', 'Préstamo Educativo')], max_length=20, verbose_name='Tipo de préstamo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto del préstamo')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa de interés mensual (%)')),
                ('plazo_meses', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Plazo (meses)')),
                ('frecuencia_pagos', models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Quincenal'), (4, 'Semanal')], verbose_name='Frecuencia de pagos')),
                ('tasa_mora', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de mora por retraso (%)')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cálculo')),
                ('total_intereses', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intereses totales')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total a pagar')),
                ('pago_periodico', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pago por período')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_prestamos', to='prestamos.cliente')),
            ],
            options={
                'verbose_name': 'Otro Préstamo',
                'verbose_name_plural': 'Otros Préstamos',
                'db_table': 'otros_prestamos',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
