# Generated by Django 4.2.20 on 2025-06-27 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_alter_cliente_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='departamento',
            field=models.CharField(choices=[('ayuntamiento', 'Ayuntamiento'), ('ferquido', 'Ferquido'), ('choga', 'Choga'), ('financiamiento', 'Financiamiento'), ('personal', 'Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 27, 17, 46, 42, 818504, tzinfo=datetime.timezone.utc)),
        ),
    ]
