# Generated by Django 4.2.20 on 2025-06-25 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_alter_prestamo_fecha_vencimiento_otroprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='otroprestamo',
            name='observacion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 2, 12, 5, 813578, tzinfo=datetime.timezone.utc)),
        ),
    ]
